AWSTemplateFormatVersion: '2010-09-09'
Description: 'ECR repository for AWS Ollama Platform - Universal Ollama container image storage'

Parameters:
  Environment:
    Type: String
    Description: 'Environment name for resource naming'
    Default: 'production'

Conditions:
  IsProduction: !Equals [!Ref Environment, 'production']

Resources:
  # Universal Ollama ECR Repository
  OllamaRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub '${Environment}-ollama'
      ImageTagMutability: MUTABLE
      ImageScanningConfiguration:
        ScanOnPush: true
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep last 10 production images",
                "selection": {
                  "tagStatus": "tagged",
                  "tagPrefixList": ["v", "latest", "stable"],
                  "countType": "imageCountMoreThan",
                  "countNumber": 10
                },
                "action": {
                  "type": "expire"
                }
              },
              {
                "rulePriority": 2,
                "description": "Keep last 5 development images",
                "selection": {
                  "tagStatus": "tagged",
                  "tagPrefixList": ["dev", "test"],
                  "countType": "imageCountMoreThan",
                  "countNumber": 5
                },
                "action": {
                  "type": "expire"
                }
              },
              {
                "rulePriority": 3,
                "description": "Delete untagged images older than 1 day",
                "selection": {
                  "tagStatus": "untagged",
                  "countType": "sinceImagePushed",
                  "countUnit": "days",
                  "countNumber": 1
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: 'aws-ollama-platform'
        - Key: Component
          Value: 'container-registry'
        - Key: ImageType
          Value: 'universal-ollama'

Outputs:
  OllamaRepositoryUri:
    Description: 'Universal Ollama ECR Repository URI'
    Value: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${OllamaRepository}'
    Export:
      Name: !Sub '${AWS::StackName}-OllamaRepositoryUri'

  OllamaRepositoryName:
    Description: 'Universal Ollama ECR Repository Name'
    Value: !Ref OllamaRepository
    Export:
      Name: !Sub '${AWS::StackName}-OllamaRepositoryName'

  RepositoryInfo:
    Description: 'Repository Information'
    Value: !Sub |
      Universal Ollama Repository: ${OllamaRepository}
      URI: ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${OllamaRepository}
      
      This single repository contains the universal Ollama image that can
      dynamically load any supported model at runtime through environment variables.
      
      Supported Models:
      - Llama2 (7B, 13B, 70B)
      - CodeLlama (7B, 13B, 34B)
      - Mistral (7B, 7B-Instruct)
      - Phi (2.7B)
      - Gemma (2B, 7B)
      - Qwen (4B, 7B, 14B)
      - DeepSeek-Coder (6.7B, 33B)
